export const MAN_THEME_LIGHT = 'MAN_THEME_LIGHT';
export const WOMAN_THEME_LIGHT = 'WOMAN_THEME_LIGHT';
export const MAN_THEME_DARK = 'MAN_THEME_DARK';
export const WOMAN_THEME_DARK = 'WOMAN_THEME_DARK';
export const SCALE_MENU = 'SCALE_MENU';

//user
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
